from erdo import *

sun_o = Value_node(1, name='Sunshine | Outdoors')
rain_o = Value_node(0, name='Rain | Outdoors')
outdoors = Uncertainty_node(name='Outdoors')
outdoors.child(sun_o, .4)
outdoors.child(rain_o, .6)
sun_p = Value_node(.95, name='Sunshine | Porch')
rain_p = Value_node(.32, name='Rain | Porch')
porch = Uncertainty_node(name='Porch')
porch.child(sun_p, .4)
porch.child(rain_p, .6)
sun_i = Value_node(.57, name='Sunshine | Indoors')
rain_i = Value_node(.67, name='Rain | Indoors')
indoors = Uncertainty_node(name='Indoors')
indoors.child(sun_i, .4)
indoors.child(rain_i, .6)
party = Decision_node(name='Party Location?')
party.child(outdoors)
party.child(porch)
party.child(indoors)
test = add_test(party, ('Outdoors','Porch','Indoors'), trueneg = .9, truepos = .9, cost=.05)
create_graph(test, filename='party')
